// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIA85pdhN6J3TJUuh3sh402WJDzxDFxD8',
    appId: '1:71626801923:web:287b416f48d2eef7435f36',
    messagingSenderId: '71626801923',
    projectId: 'weathermonitoring-155ed',
    authDomain: 'weathermonitoring-155ed.firebaseapp.com',
    databaseURL: 'https://weathermonitoring-155ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weathermonitoring-155ed.appspot.com',
    measurementId: 'G-P4VQYN9NWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfv4EZCYbT6BBF_umfSJkP-SgE2p2M8oU',
    appId: '1:71626801923:android:4d9861ef3dbbff04435f36',
    messagingSenderId: '71626801923',
    projectId: 'weathermonitoring-155ed',
    databaseURL: 'https://weathermonitoring-155ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weathermonitoring-155ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS8-BoZdQlY955f1-g8BDfo8OBwX0DkQ4',
    appId: '1:71626801923:ios:d17b4447a65af08f435f36',
    messagingSenderId: '71626801923',
    projectId: 'weathermonitoring-155ed',
    databaseURL: 'https://weathermonitoring-155ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weathermonitoring-155ed.appspot.com',
    iosBundleId: 'com.example.weathermonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIA85pdhN6J3TJUuh3sh402WJDzxDFxD8',
    appId: '1:71626801923:web:a3351177d301625f435f36',
    messagingSenderId: '71626801923',
    projectId: 'weathermonitoring-155ed',
    authDomain: 'weathermonitoring-155ed.firebaseapp.com',
    databaseURL: 'https://weathermonitoring-155ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weathermonitoring-155ed.appspot.com',
    measurementId: 'G-GFXF6NNTN9',
  );
}
